web:
  build: ./wp
  command: php -S 0.0.0.0:8000 -t /wp
#  command: service apache2 start
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - ./wp:/wp
db:
  image: orchardup/mysql
  environment:
    MYSQL_DATABASE: gs
    MYSQL_ROOT_PASSWORD: gentlesport
    MYSQL_USER: dbadmin
    MYSQL_PASSWORD: gentlesport
  ports:
    - "3306:3306"