web:
  container_name: web
  build: ./wp
#  image: havetisyan/docker:website_web
  command: php -S 0.0.0.0:8000 -t /code
#  command: service apache2 start
  ports:
    - "8000:8000"
    - "80:80"
  links:
    - db
  volumes:
    - ./wp:/code
  environment:
    - DEBUG=true
#  service: web
db:
  container_name: db
  #image: orchardup/mysql
  image: havetisyan/docker:website_db
  environment:
    MYSQL_DATABASE: gs
    MYSQL_ROOT_PASSWORD: gentlesport
    MYSQL_USER: dbadmin
    MYSQL_PASSWORD: gentlesport
  ports:
    - "3306:3306"